/* eslint-disable no-redeclare, no-unused-vars */
// This file is generated by `npm run build`.
// remap parameter names from cordova.define
// see `externals` in webpack.cordova.config.js
const cordovaRequire = require;
const cordovaExports = exports;
const cordovaModule = module;
